#!/usr/bin/env python
# -*- coding: utf-8 -*-

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .checks import (
        check_args_types,
        is_builtin_collection,
        is_builtin_number,
        is_builtin_obj,
        is_builtin_scalar,
        is_dataclass_instance,
        is_iterable_bool,
        is_iterable_bytes_or_list,
        is_iterable_float,
        is_iterable_int,
        is_iterable_integral,
        is_iterable_str,
        is_namedtuple_instance,
        is_sequence_str,
        is_typed_dict,
        isinstance_generic,
    )
    from .classes import (
        BuiltinCollection,
        BuiltinNumber,
        BuiltinScalar,
        DataclassInstance,
        EllipsisType,
        ListOrTuple,
        NamedTupleInstance,
        NoneType,
        SupportsAdd,
        SupportsAnd,
        SupportsBool,
        SupportsDiv,
        SupportsGetitem,
        SupportsGetitem2,
        SupportsGetitemIterLen,
        SupportsGetitemIterLen2,
        SupportsGetitemLen,
        SupportsGetitemLen2,
        SupportsIterLen,
        SupportsLen,
        SupportsMatmul,
        SupportsMul,
        SupportsOr,
        T_BuiltinNumber,
        T_BuiltinScalar,
    )

else:
    import lazy_loader as lazy

    __getattr__, __dir__, __all__ = lazy.attach(
        __name__,
        submodules=[
            "checks",
            "classes",
        ],
        submod_attrs={
            "checks": [
                "check_args_types",
                "is_builtin_collection",
                "is_builtin_number",
                "is_builtin_obj",
                "is_builtin_scalar",
                "is_dataclass_instance",
                "is_iterable_bool",
                "is_iterable_bytes_or_list",
                "is_iterable_float",
                "is_iterable_int",
                "is_iterable_integral",
                "is_iterable_str",
                "is_namedtuple_instance",
                "is_sequence_str",
                "is_typed_dict",
                "isinstance_generic",
            ],
            "classes": [
                "BuiltinCollection",
                "BuiltinNumber",
                "BuiltinScalar",
                "DataclassInstance",
                "EllipsisType",
                "ListOrTuple",
                "NamedTupleInstance",
                "NoneType",
                "SupportsAdd",
                "SupportsAnd",
                "SupportsBool",
                "SupportsDiv",
                "SupportsGetitem",
                "SupportsGetitem2",
                "SupportsGetitemIterLen",
                "SupportsGetitemIterLen2",
                "SupportsGetitemLen",
                "SupportsGetitemLen2",
                "SupportsIterLen",
                "SupportsLen",
                "SupportsMatmul",
                "SupportsMul",
                "SupportsOr",
                "T_BuiltinNumber",
                "T_BuiltinScalar",
            ],
        },
    )
